# Generated by Django 3.0.1 on 2022-01-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songname', models.CharField(max_length=60)),
                ('artist', models.CharField(max_length=60)),
                ('release_year', models.IntegerField()),
                ('genre', models.TextField()),
            ],
        ),
    ]
