# Generated by Django 3.0.1 on 2022-01-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlist',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
